# Verwende Node.js als Basis-Image
FROM node:20

# Setze das Arbeitsverzeichnis im Container
WORKDIR /app

# Kopiere package.json und package-lock.json
COPY package*.json ./

# Installiere die Abhängigkeiten
RUN npm install

# Kopiere den Rest des Codes
COPY . .

# Setze die Umgebungsvariablen
ENV PORT=5000
ENV DB_HOST=mysql
ENV DB_USER=root
ENV DB_PASS=Marsone1142//
ENV DB_NAME=shop

# Öffne den Port 5000 im Container
EXPOSE 5000

# Starte den Server
CMD ["node", "server.js"]
